application: finepieces4cgk
version: 1
runtime: python27
api_version: 1
threadsafe: True

handlers:
  
- url: /static/
  static_dir: static

- url: .*
  script: finepieces4cgk.app
  
  
libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
- name: PIL
  version: "1.1.7"
